// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function ChooseDirectory():Promise<string>;

export function Download(arg1:string,arg2:config.DownloadOptions):Promise<void>;
