// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDirectory() {
  return window['go']['download']['Downloader']['ChooseDirectory']();
}

export function Defaults() {
  return window['go']['download']['Downloader']['Defaults']();
}

export function Download(arg1, arg2) {
  return window['go']['download']['Downloader']['Download'](arg1, arg2);
}
