// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {download} from '../models';

export function ChooseDirectory():Promise<string>;

export function Download(arg1:download.Options):Promise<void>;
