// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDirectory() {
  return window['go']['app']['App']['ChooseDirectory']();
}

export function DarkMode() {
  return window['go']['app']['App']['DarkMode']();
}

export function Download(arg1, arg2) {
  return window['go']['app']['App']['Download'](arg1, arg2);
}

export function LightMode() {
  return window['go']['app']['App']['LightMode']();
}

export function ResetMode() {
  return window['go']['app']['App']['ResetMode']();
}

export function Settings() {
  return window['go']['app']['App']['Settings']();
}

export function UpdateSettings(arg1) {
  return window['go']['app']['App']['UpdateSettings'](arg1);
}
