// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ChooseDirectory():Promise<string>;

export function Download(arg1:app.Options):Promise<void>;
