// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function Load():Promise<config.Settings>;

export function Update(arg1:config.Settings):Promise<void>;
