// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Load() {
  return window['go']['config']['Manager']['Load']();
}

export function Update(arg1) {
  return window['go']['config']['Manager']['Update'](arg1);
}
