// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DarkMode():Promise<void>;

export function LightMode():Promise<void>;

export function ResetMode():Promise<void>;
