// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DarkMode() {
  return window['go']['theme']['Settings']['DarkMode']();
}

export function LightMode() {
  return window['go']['theme']['Settings']['LightMode']();
}

export function ResetMode() {
  return window['go']['theme']['Settings']['ResetMode']();
}
